### ISSUE TITLE
Add Client

### ISSUE THREAD

**Issue by PV-Patrick** [mgufrone/whmcs-api#2]
It seems like whenever I add a new client, the process runs and it generates a new client via the API but then your package returns an error saying that the email address has already been used...  I know 100% the Email address is not in the tblclients or tblcontacts database prior to this addclient so this seems to be a bug.  Can you confirm this?  Thank you!

WHMCS: 5.3.11

I did some more testing and this is what I came up with.  For some reason, the moment I exec the WHMCS API call within the Laravel Validation passes() function, it reruns the validation again, causing it to loop through the WHMCS API call all over again.  This does not happen when I comment out the Whmcs::execute function.

**Comment by mgufrone** [comment]
can you leave your code about how you call whmcs add new client api here?

**Comment by mgufrone** [comment]
when i using this, it gives me result as expected
```php
Route::get('/', function()
{
	Config::set('whmcs::username', 'username');
	Config::set('whmcs::password', 'password');
	Config::set('whmcs::responsetype', 'json');
	Config::set('whmcs::url', 'url');

	$call = Whmcs::addclient([
		'email'=>'emailtest@gmail.com',
		'firstname'=>'Mochamad',
		'lastname'=>'Gufy',
		'address1'=>'Gedangan',
		'city'=>'Sidoarjo',
		'state'=>'East Java',
		'postcode'=>'61254',
		'phonenumber'=>'190238019',
		'country'=>'ID',
	]);
	return json_encode($call);
});
```

**Comment by PV-Patrick** [comment]
Hello!

In my routes.php I have:
`Route::post('order/process', 'OrderController@process');`

In my OrderController.php I have:
```php
public function process()
{
	mail('patrick@pure-voice.net', 'Test', '');
	// -- Payment nonce from Braintree - contains payment information
	$nonce = Input::get('payment_method_nonce');

	$validator = new OrderFormValidator(Input::all());
	if ($validator->passes()) {

		// -- Passed Validation, continue with account creation.
		// -- Check if we have already created a client/order/invoice and this is just a retry from failed payment.
		if(Session::has('prev_clientid')) {

		} else {
			
			// -- 1. Add Customer to WHMCS
			$cust_array = array(
				'firstname'		=> Input::get('firstname'),
				'lastname'		=> Input::get('lastname'),
				'companyname'	=> Input::get('companyname'),
				'email'			=> Input::get('email'),
				'phonenumber'	=> Input::get('phonenumber'),
				'address1'		=> Input::get('address1'),
				'city'			=> Input::get('city'),
				'state'			=> Input::get('state'),
				'postcode'		=> Input::get('postcode'),
				'country'		=> Input::get('country'),
				'password2'		=> Input::get('password'),
				'clientip'		=> Request::getClientIp(),
				'groupid'		=> '1'
			);
			$addclient = Whmcs::execute('addclient', $cust_array);
			//dd(Whmcs::execute('addclient', $cust_array));
			
		}

	} else {
		dd('Validation Failed');
		// -- Form did not validate, return back with errors
		return Redirect::back()->withInput()->withErrors($validator->errors());
	}
}`

This causes the validation to run twice when I run the ```php $addclient = Whmcs::execute('addclient', $cust_array);` command.  I couldn't find anything related in your library so maybe it's from guzzlehttp?  Thanks!

**Comment by PV-Patrick** [comment]
I just tested it using `$call = Whmcs::addclient();` vs `$call = Whmcs::execute();` and the result was the same, double validation execution.

**Comment by mgufrone** [comment]
do you mean the whmcs validation? if so, you can pass `'skipvalidation'=>'true'` in your parameters, so it won't validate again.

**Comment by PV-Patrick** [comment]
no, the laraval validation runs twice. The entire process runs twice.

**Comment by PV-Patrick** [comment]
@mgufrone I figured it out today that the client-side js validation I was running was causing the form to submit a 2nd time and not actually your class.  During testing, sometimes it would submit twice and sometimes it wouldn't and I think it was just coincidence that the moment I removed the exec line from your library it only submitted once.

You can close this out and my apologies for the waste in time!

**Comment by mgufrone** [comment]
no problem. thank you for using this package. :)
