### ISSUE TITLE
Publish config Too many arguments.  

### ISSUE THREAD

**Issue by kayyyy** [mgufrone/whmcs-api#3]
If i run i get this error in Laravel5 with WHMCS 6.0

```
php artisan vendor:publish gufy/whmcs
      
  [RuntimeException]   
  Too many arguments.  
```

I copied the config file manually

And then if i want to login a user i get the exception `GuzzleHttp \ Exception \ ParseException
HELP
Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON`

**Comment by mgufrone** [comment]
I'll go check it out.

**Comment by mgufrone** [comment]
You don't have to put this package name while you run `vendor:publish` command.

just use
```
php artisan vendor:publish
```

it will publish all registered vendors

**Comment by kayyyy** [comment]
```
vagrant@homestead:~/Code/hosting$ php artisan vendor:publish
                                                         
  [ErrorException]                                                
  The use statement with non-compound name 'Whmcs' has no effect  
                                                               
```

Laravel 5.0 with `"gufy/whmcs": "~2"`
