### ISSUE TITLE
guzzle

### ISSUE THREAD

**Issue by exwizzard** [mgufrone/whmcs-api#5]
Can you please update? 

 Problem 1
    - Installation request for gufy/whmcs ~2 -> satisfiable by gufy/whmcs[v2.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.1.1
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - gufy/whmcs v2.0.0 requires guzzlehttp/guzzle ~5 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.x-dev].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.x-dev, 6.1.1].
    - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

**Comment by mgufrone** [comment]
Done. Try it again. :+1:
