### ISSUE TITLE
Not working - nable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON"

### ISSUE THREAD

**Issue by faralimite** [mgufrone/whmcs-api#6]
Hello,

There is an error with the GuzzleHttp because the user-agent is not defined.

Error: 
"ParseException in Response.php line 148: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON"

Fix:
1. open: vendor/gufy/whmcs/src/Gufy/Whmcs/Whmcs.php
2. replace line 38 $client = new Client; with $client = new Client(['defaults' => ['headers' => ['User-Agent' => null]]]);

Please update the repository because it's a pity to have a nice  package not working.

Regards,
Radu

**Comment by mgufrone** [comment]
Done. thanks for reporting. :+1:
