### ISSUE TITLE
Guzzle.

### ISSUE THREAD

**Issue by hazaveh** [mgufrone/whmcs-api#7]
Problem 1
    - gufy/whmcs v2.0.1 requires guzzlehttp/guzzle ~5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - gufy/whmcs v2.0.3 requires guzzlehttp/guzzle ~5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.0
    - Conclusion: remove guzzlehttp/guzzle 6.1.1
    - Installation request for gufy/whmcs ^2.0 -> satisfiable by gufy/whmcs[v2.0.0, v2.0.1, v2.0.3].
    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - gufy/whmcs v2.0.0 requires guzzlehttp/guzzle ~5 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
    - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

**Comment by mgufrone** [comment]
Fixed, try the latest update
